version: "3.3"

services:
  mis-project-front-dev:
    image: nginx:alpine
    container_name: mis-project-front-dev
    volumes:
      - ./build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    restart: unless-stopped