name: Build

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Log into docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.IMAGE_NAME }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.IMAGE_NAME }}:${{ github.ref_name }},${{ vars.IMAGE_NAME }}:latest
